### ISSUE TITLE
panic: can't use ElementIterator on unknown value

### ISSUE THREAD

**Issue by syphernl** [aquasecurity/tfsec#1017]
**Describe the bug**

Running tfsec 0.58.0 on our codebase results in an error.

```sh
[DEBUG][2021-08-12 13:18:11.927638293 +0200 CEST m=+0.342038321] Loaded module '/home/frank/dev/gitlab/PROJECT/.terraform/modules/vpc.label' (requested at /home/frank/dev/gitlab/PROJECT/.terraform/modules/ecr/context.tf:21-41)
[DEBUG][2021-08-12 13:18:11.927806275 +0200 CEST m=+0.342206303] Starting iteration 1 of context evaluation...
[DEBUG][2021-08-12 13:18:11.928293046 +0200 CEST m=+0.342693073] Starting iteration 1 of context evaluation...
[DEBUG][2021-08-12 13:18:11.928636242 +0200 CEST m=+0.343036270] Starting iteration 2 of context evaluation...
[DEBUG][2021-08-12 13:18:11.929259013 +0200 CEST m=+0.343659046] Starting iteration 3 of context evaluation...
[DEBUG][2021-08-12 13:18:11.931779313 +0200 CEST m=+0.346179368] Loading modules...
[DEBUG][2021-08-12 13:18:11.932164423 +0200 CEST m=+0.346564457] Starting iteration 1 of context evaluation...
[DEBUG][2021-08-12 13:18:11.934949352 +0200 CEST m=+0.349349390] Starting iteration 2 of context evaluation...
[DEBUG][2021-08-12 13:18:11.935632858 +0200 CEST m=+0.350032897] Module [this:/home/frank/dev/gitlab/PROJECT/.terraform/modules/vpc.label:module.this] has already been seen
[DEBUG][2021-08-12 13:18:11.936053328 +0200 CEST m=+0.350453361] Starting iteration 1 of context evaluation...
[DEBUG][2021-08-12 13:18:11.936413931 +0200 CEST m=+0.350813959] Starting iteration 2 of context evaluation...
[DEBUG][2021-08-12 13:18:11.937043635 +0200 CEST m=+0.351443664] Starting iteration 3 of context evaluation...
[DEBUG][2021-08-12 13:18:11.937877407 +0200 CEST m=+0.352277438] Loading modules...
[DEBUG][2021-08-12 13:18:11.937954345 +0200 CEST m=+0.352354375] Starting iteration 1 of context evaluation...
[DEBUG][2021-08-12 13:18:11.938951623 +0200 CEST m=+0.353351650] Starting iteration 1 of context evaluation...
[DEBUG][2021-08-12 13:18:11.93974002 +0200 CEST m=+0.354140048] Starting iteration 2 of context evaluation...
panic: can't use ElementIterator on unknown value

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.ElementIterator(0xcbc728, 0xc0003b5bd0, 0xac8f40, 0x1124380, 0x2, 0x0)
	/home/runner/work/tfsec/tfsec/vendor/github.com/zclconf/go-cty/cty/value_ops.go:1118 +0x13b
github.com/zclconf/go-cty/cty.Value.AsValueMap(0xcbc728, 0xc0003b5bd0, 0xac8f40, 0x1124380, 0xc0012fd740)
	/home/runner/work/tfsec/tfsec/vendor/github.com/zclconf/go-cty/cty/value_ops.go:1326 +0x10b
github.com/aquasecurity/tfsec/internal/app/tfsec/block.mergeObjects(0xcbc728, 0xc0003b5bd0, 0xac8f40, 0x1124380, 0xcbc728, 0xc00029d990, 0xac8f40, 0x1124380, 0xcbc728, 0xc0002d38f0, ...)
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/block/context.go:110 +0xca
github.com/aquasecurity/tfsec/internal/app/tfsec/block.mergeObjects(0xcbc728, 0xc00029dc40, 0xad3140, 0xc000f307e0, 0xcbc728, 0xc0003b5c80, 0xad3140, 0xc001e47680, 0xcbc728, 0xc0002d3810, ...)
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/block/context.go:116 +0x555
github.com/aquasecurity/tfsec/internal/app/tfsec/block.mergeObjects(0xcbc728, 0xc00021f640, 0xad3140, 0xc001a58090, 0xcbc728, 0xc0002c39b0, 0xad3140, 0xc0010cb2c0, 0xcbc728, 0xc000242b40, ...)
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/block/context.go:116 +0x555
github.com/aquasecurity/tfsec/internal/app/tfsec/block.mergeVars(0xcbc728, 0xc00021f640, 0xad3140, 0xc001a58090, 0xc00251f110, 0x0, 0x0, 0xcbc728, 0xc0002c39b0, 0xad3140, ...)
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/block/context.go:87 +0x216
github.com/aquasecurity/tfsec/internal/app/tfsec/block.(*Context).Set(0xc0003ae250, 0xcbc728, 0xc0002c39b0, 0xad3140, 0xc0010cb2c0, 0xc00251f110, 0x1, 0x1)
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/block/context.go:79 +0x125
github.com/aquasecurity/tfsec/internal/app/tfsec/parser.(*Evaluator).evaluateStep(0xc002380240, 0x1)
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/parser/evaluator.go:77 +0x246
github.com/aquasecurity/tfsec/internal/app/tfsec/parser.(*Evaluator).EvaluateAll(0xc002380240, 0x2d, 0xc00031a640, 0x4b, 0xc00071b000, 0x86)
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/parser/evaluator.go:141 +0x16c
github.com/aquasecurity/tfsec/internal/app/tfsec/parser.(*Evaluator).evaluateModules(0xc00011a000)
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/parser/evaluator.go:114 +0x31b
github.com/aquasecurity/tfsec/internal/app/tfsec/parser.(*Evaluator).evaluateStep(0xc00011a000, 0x0)
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/parser/evaluator.go:90 +0x5e5
github.com/aquasecurity/tfsec/internal/app/tfsec/parser.(*Evaluator).EvaluateAll(0xc00011a000, 0xb6e275, 0x7, 0x2d, 0xc0007c0000, 0x73)
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/parser/evaluator.go:164 +0x4c5
github.com/aquasecurity/tfsec/internal/app/tfsec/parser.(*Parser).ParseDirectory(0xc0001d20c0, 0x2d, 0xc000374020, 0x1, 0x1, 0xc0001d20c0)
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/parser/parser.go:106 +0xa2d
main.glob..func2(0x10c79c0, 0xc00036cef0, 0x0, 0x1, 0x0, 0x0)
	/home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:213 +0x69e
github.com/spf13/cobra.(*Command).execute(0x10c79c0, 0xc00001e050, 0x1, 0x1, 0x10c79c0, 0xc00001e050)
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x10c79c0, 0xc00005c778, 0xc0006bff78, 0x406365)
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:902
main.main()
	/home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:91 +0x31
```

The module it appears to be failing on is https://github.com/cloudposse/terraform-null-label.

I have tested this against a few Terraform projects and it seems to work 50% of the time. In other projects it is failing on other modules, but showing the same error.
If I remove the `.terraform` folder, `tfsec` works just fine (but complains that it cannot load the modules).

**To Reproduce**
1. Run tfsec on a `terraform init`-ed folder.
2. See error

**Expected behavior**
No errors or better error on what goes wrong.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Terraform v1.0.4
 - tfsec v0.58.0

**Comment by liamg** [comment]
Hey @syphernl - please could you try the `v0.58.1-prerelease` that is building now?

**Comment by liamg** [comment]
See https://github.com/aquasecurity/tfsec/releases/tag/v0.58.1-prerelease

**Comment by syphernl** [comment]
@liamg I can confirm that the error is gone when using the 0.58.1-prelease version. Thanks for the fast reply & solution!

**Comment by liamg** [comment]
@syphernl Awesome, thanks, v0.58.1 is now tagged :+1:
