### ISSUE TITLE
bug: panic: value is null / stack trace with warnings for `terraform init` ; Error: Unexpected end of JSON input

### ISSUE THREAD

**Issue by kbroughton** [aquasecurity/tfsec#1467]
**Describe the bug**
This is running on a large terraform project and it would be difficult to create a minimal case that will reproduce the problem.
However, it seems related to recent changes Jan 28 in tfsec and since there is a line of code throwing a panic/stack trace, it seems reasonable that you may want to wrap that with some error handling. 

Note that we have other issues with our tfsec. Aug 17, our runs stopped uploading to Github Advanced Security even with valid tfsec.sarif files. There have been a lot of changes in tfsec/defsec and underlying https://github.com/github/codeql-action which seem to have exposed latent bugs.  tfsec was generating a tfsec.sarif with valid json with the `terraform init` WARNINGs present in the logs until Jan 28, 2022. 

```
+ tfsec --format=sarif .
WARNING: Did you forget to 'terraform init'? The following modules failed to load:
 - git@github.com:rigup/terraform-google-legacy-sql.git?ref=v1.0.1
 - terraform-google-modules/vm/google//modules/compute_instance
 - terraform-google-modules/vm/google//modules/instance_template
 - terraform-google-modules/cloud-storage/google//modules/simple_bucket
 - ./modules/workspaces
 - ./modules/cluster
 - ./modules/namespace
 - github.com/gruntwork-io/terraform-google-load-balancer.git//modules/http-load-balancer?ref=tf12
 - terraform-google-modules/cloud-router/google
 - github.com/gruntwork-io/terraform-google-load-balancer.git//modules/http-load-balancer?ref=v0.4.2
WARNING: Did you forget to 'terraform init'? The following modules failed to load:
 - GoogleCloudPlatform/sql-db/google//modules/postgresql
panic: value is null

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.AsString({{{0xd10e38, 0xc00002fb51}}, {0x0, 0x0}})
	/home/runner/work/tfsec/tfsec/vendor/github.com/zclconf/go-cty/cty/value_ops.go:1254 +0x125
github.com/aquasecurity/tfsec/internal/pkg/adapter/google/gke.(*adapter).adaptCluster.func1({{{0xd10e38, 0xc00002fb51}}, {0xaba6c0, 0xc00fec1ae0}}, {{{0xd10e38, 0xc00002fb51}}, {0x0, 0x0}})
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/google/gke/adapt.go:134 +0x9a
github.com/aquasecurity/tfsec/internal/pkg/block.(*Attribute).Each.func1({{{0xd10e38, 0xc00002fb51}}, {0xaba6c0, 0xc00fec1ae0}}, {{{0xd10e38, 0xc00002fb51}}, {0x0, 0x0}})
	/home/runner/work/tfsec/tfsec/internal/pkg/block/attribute.go:182 +0x4c
github.com/zclconf/go-cty/cty.Value.ForEachElement({{{0xd10f18, 0xc00fec1ad0}}, {0xae42c0, 0xc0104c1320}}, 0xc0122d8fd0)
	/home/runner/work/tfsec/tfsec/vendor/github.com/zclconf/go-cty/cty/value_ops.go:1144 +0x9a
github.com/aquasecurity/tfsec/internal/pkg/block.(*Attribute).Each(0x0, 0xc0122d9190)
	/home/runner/work/tfsec/tfsec/internal/pkg/block/attribute.go:181 +0x4b
github.com/aquasecurity/tfsec/internal/pkg/adapter/google/gke.(*adapter).adaptCluster(0xc0122da2f8, 0xc000e06280, 0x8)
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/google/gke/adapt.go:133 +0xea5
github.com/aquasecurity/tfsec/internal/pkg/adapter/google/gke.(*adapter).adaptClusters(0xc0122da2f8)
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/google/gke/adapt.go:28 +0x3a8
github.com/aquasecurity/tfsec/internal/pkg/adapter/google/gke.Adapt(...)
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/google/gke/adapt.go:16
github.com/aquasecurity/tfsec/internal/pkg/adapter/google.Adapt({_, _, _})
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/google/adapt.go:21 +0x25d
github.com/aquasecurity/tfsec/internal/pkg/adapter.Adapt({0xc006d6f000, 0x4e8, 0x600})
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/adapt.go:24 +0x230
github.com/aquasecurity/tfsec/internal/pkg/scanner.(*Scanner).Scan(0xc00c22f5c0, {0xc006d6f000, 0x0, 0x600})
	/home/runner/work/tfsec/tfsec/internal/pkg/scanner/scanner.go:51 +0x9f
github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.glob..func1(0x127a1a0, {0xc0003e6060, 0x1, 0x2})
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/cmd/root.go:114 +0x7ec
github.com/spf13/cobra.(*Command).execute(0x127a1a0, {0xc00001e190, 0x2, 0x2})
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x127a1a0)
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:902
main.main()
	/home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:11 +0x25
+ tfsec_return=2
+ exit_code=2
+ echo ::set-output name=tfsec-return-code::2
```

**To Reproduce**
Steps to reproduce the behavior: (looks like it would be)
1. create minimal main.tf perhaps with gke resources and perpas with for_each logic
2. do not `terraform init` # this is common if you have remote state and haven't wired up credentials
     for example, if cutting and pasting tfsec-sarif-action into a github action
3. run the terraform-sarif-action github action on the repo

**Expected behavior**
Any errors due to failing to init or other missing data should report on the specific missing data and not throw a stacktrace.

**Screenshots**

**Desktop (please complete the following information):**
 - mac-osx 

```terraform -version
Terraform v1.0.11
on darwin_amd64
```

**Additional context**

**Comment by liamg** [comment]
Thanks, `v1.0.8` is building now with this fix.
