### ISSUE TITLE
bug: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by roryprimrose** [aquasecurity/tfsec#1469]
**Describe the bug**
The tfsec CLI is failing on an invalid memory address

**To Reproduce**

We run the following command in a Ubuntu agent in Azure DevOps.

```
/agent/_work/_temp/5b5f658c-77eb-489e-b047-9ddcc7d90a6a/tfsec-linux-amd64 --include-passed --soft-fail --run-statistics --debug  '/agent/_work/1/s
```

The debug log for this is:

```
##[command]/agent/_work/_temp/5b5f658c-77eb-489e-b047-9ddcc7d90a6a/tfsec-linux-amd64 --version
v1.0.7
##[command]/agent/_work/_temp/5b5f658c-77eb-489e-b047-9ddcc7d90a6a/tfsec-linux-amd64 --include-passed --soft-fail --run-statistics --debug  '/agent/_work/1/s'
[DEBUG][2022-01-31 22:21:49.205201157 +0000 UTC m=+0.004036214] loading config file /agent/_work/1/s/.tfsec/config.json
[DEBUG][2022-01-31 22:21:49.205801689 +0000 UTC m=+0.004636746] Loading custom checks...
[DEBUG][2022-01-31 22:21:49.20618991 +0000 UTC m=+0.005024867] Using the default custom check folder
[DEBUG][2022-01-31 22:21:49.206536928 +0000 UTC m=+0.005371885] custom check directory set to /agent/_work/1/s/.tfsec
[DEBUG][2022-01-31 22:21:49.206982951 +0000 UTC m=+0.005818008] Custom checks loaded
[DEBUG][2022-01-31 22:21:49.20733777 +0000 UTC m=+0.006172727] checking for tfvars files using glob: /agent/_work/1/s/*.tfvars
[DEBUG][2022-01-31 22:21:49.207766393 +0000 UTC m=+0.006601350] Starting parser...
[DEBUG][2022-01-31 22:21:49.208236518 +0000 UTC m=+0.007071575] Finding Terraform subdirectories...
[DEBUG][2022-01-31 22:21:49.208787447 +0000 UTC m=+0.007622504] Found qualifying subdirectory containing .tf files: /agent/_work/1/s
[DEBUG][2022-01-31 22:21:49.209342176 +0000 UTC m=+0.008177233] Beginning parse for directory '/agent/_work/1/s'...
[DEBUG][2022-01-31 22:21:49.212467141 +0000 UTC m=+0.011302098] Added 2 blocks from /agent/_work/1/s/providers.tf...
[DEBUG][2022-01-31 22:21:49.212974168 +0000 UTC m=+0.011809125] Added 4 blocks from /agent/_work/1/s/variables.tf...
[DEBUG][2022-01-31 22:21:49.213432592 +0000 UTC m=+0.012267549] Added 1 blocks from /agent/_work/1/s/backend.tf...
[DEBUG][2022-01-31 22:21:49.214027323 +0000 UTC m=+0.012862280] Added 15 blocks from /agent/_work/1/s/main.tf...
[DEBUG][2022-01-31 22:21:49.214580652 +0000 UTC m=+0.013415709] Project root set to '/agent/_work/1/s'...
[DEBUG][2022-01-31 22:21:49.214985474 +0000 UTC m=+0.013820431] Loading TFVars...
[DEBUG][2022-01-31 22:21:49.215354993 +0000 UTC m=+0.014189950] Loading module metadata...
[DEBUG][2022-01-31 22:21:49.215820618 +0000 UTC m=+0.014655575] Evaluating expressions...
[DEBUG][2022-01-31 22:21:49.216303143 +0000 UTC m=+0.015138100] Starting iteration 1 of context evaluation...
[DEBUG][2022-01-31 22:21:49.217008581 +0000 UTC m=+0.015843638] Starting iteration 2 of context evaluation...
[DEBUG][2022-01-31 22:21:49.217821324 +0000 UTC m=+0.016656281] Starting iteration 3 of context evaluation...
[DEBUG][2022-01-31 22:21:49.218761473 +0000 UTC m=+0.017596530] Loading modules...
[DEBUG][2022-01-31 22:21:49.2192697 +0000 UTC m=+0.018104757] Added module.featurepreview-appconfig from count var
[DEBUG][2022-01-31 22:21:49.220819682 +0000 UTC m=+0.019654739] Added 3 blocks from /agent/_work/1/s/.terraform/modules/azure-mssql-database/main.tf...
[DEBUG][2022-01-31 22:21:49.223001197 +0000 UTC m=+0.021836154] Added 1 blocks from /agent/_work/1/s/.terraform/modules/azure-mssql-database/outputs.tf...
[DEBUG][2022-01-31 22:21:49.223487623 +0000 UTC m=+0.022322580] Added 1 blocks from /agent/_work/1/s/.terraform/modules/azure-mssql-database/providers.tf...
[DEBUG][2022-01-31 22:21:49.223989149 +0000 UTC m=+0.022824106] Added 7 blocks from /agent/_work/1/s/.terraform/modules/azure-mssql-database/variables.tf...
[DEBUG][2022-01-31 22:21:49.224591781 +0000 UTC m=+0.023426738] Loaded module '/agent/_work/1/s/.terraform/modules/azure-mssql-database' (requested at /agent/_work/1/s/main.tf:51-60)
[DEBUG][2022-01-31 22:21:49.227968659 +0000 UTC m=+0.026803616] Added 12 blocks from /agent/_work/1/s/.terraform/modules/featurepreview-fa/main.tf...
[DEBUG][2022-01-31 22:21:49.228764601 +0000 UTC m=+0.027599558] Added 4 blocks from /agent/_work/1/s/.terraform/modules/featurepreview-fa/outputs.tf...
[DEBUG][2022-01-31 22:21:49.229257327 +0000 UTC m=+0.028092284] Added 1 blocks from /agent/_work/1/s/.terraform/modules/featurepreview-fa/providers.tf...
[DEBUG][2022-01-31 22:21:49.229819257 +0000 UTC m=+0.028654314] Added 21 blocks from /agent/_work/1/s/.terraform/modules/featurepreview-fa/variables.tf...
[DEBUG][2022-01-31 22:21:49.230377886 +0000 UTC m=+0.029212843] Loaded module '/agent/_work/1/s/.terraform/modules/featurepreview-fa' (requested at /agent/_work/1/s/main.tf:65-92)
[DEBUG][2022-01-31 22:21:49.231707157 +0000 UTC m=+0.030542114] Added 8 blocks from /agent/_work/1/s/.terraform/modules/featurepreview-appconfig/main.tf...
[DEBUG][2022-01-31 22:21:49.232257886 +0000 UTC m=+0.031092843] Added 1 blocks from /agent/_work/1/s/.terraform/modules/featurepreview-appconfig/outputs.tf...
[DEBUG][2022-01-31 22:21:49.232885019 +0000 UTC m=+0.031719976] Added 1 blocks from /agent/_work/1/s/.terraform/modules/featurepreview-appconfig/providers.tf...
[DEBUG][2022-01-31 22:21:49.233392346 +0000 UTC m=+0.032227403] Added 4 blocks from /agent/_work/1/s/.terraform/modules/featurepreview-appconfig/variables.tf...
[DEBUG][2022-01-31 22:21:49.23384827 +0000 UTC m=+0.032683227] Loaded module '/agent/_work/1/s/.terraform/modules/featurepreview-appconfig' (requested at /agent/_work/1/s/main.tf:97-104)
[DEBUG][2022-01-31 22:21:49.234348496 +0000 UTC m=+0.033183553] Added module.featurepreview-appconfig from count var
[DEBUG][2022-01-31 22:21:49.234793119 +0000 UTC m=+0.033628076] Starting iteration 1 of context evaluation...
[DEBUG][2022-01-31 22:21:49.235685367 +0000 UTC m=+0.034520424] Starting iteration 1 of context evaluation...
[DEBUG][2022-01-31 22:21:49.236185993 +0000 UTC m=+0.035020950] Starting iteration 2 of context evaluation...
[DEBUG][2022-01-31 22:21:49.236913831 +0000 UTC m=+0.035748888] Loading modules...
[DEBUG][2022-01-31 22:21:49.23745086 +0000 UTC m=+0.036285817] Starting iteration 1 of context evaluation...
[DEBUG][2022-01-31 22:21:49.238065092 +0000 UTC m=+0.036900049] Starting iteration 2 of context evaluation...
[DEBUG][2022-01-31 22:21:49.238918937 +0000 UTC m=+0.037753994] Starting iteration 1 of context evaluation...
[DEBUG][2022-01-31 22:21:49.239898889 +0000 UTC m=+0.038733846] Starting iteration 2 of context evaluation...
[DEBUG][2022-01-31 22:21:49.241124654 +0000 UTC m=+0.039959711] Loading modules...
[DEBUG][2022-01-31 22:21:49.241583978 +0000 UTC m=+0.040418935] Added azurerm_app_service_virtual_network_swift_connection.this from count var
[DEBUG][2022-01-31 22:21:49.242129807 +0000 UTC m=+0.040964764] Added azurerm_private_endpoint.functionapp from count var
[DEBUG][2022-01-31 22:21:49.242783741 +0000 UTC m=+0.041618698] Added azurerm_function_app_slot.staging from count var
[DEBUG][2022-01-31 22:21:49.243398174 +0000 UTC m=+0.042233231] Added azurerm_app_service_slot_virtual_network_swift_connection.staging from count var
[DEBUG][2022-01-31 22:21:49.24407711 +0000 UTC m=+0.042912167] Added azurerm_private_endpoint.functionapp_slot from count var
[DEBUG][2022-01-31 22:21:49.244718643 +0000 UTC m=+0.043553600] Starting iteration 1 of context evaluation...
[DEBUG][2022-01-31 22:21:49.245915107 +0000 UTC m=+0.044750064] Starting iteration 2 of context evaluation...
[DEBUG][2022-01-31 22:21:49.249290385 +0000 UTC m=+0.048125342] Starting iteration 1 of context evaluation...
[DEBUG][2022-01-31 22:21:49.249859415 +0000 UTC m=+0.048694372] Starting iteration 2 of context evaluation...
[DEBUG][2022-01-31 22:21:49.250467747 +0000 UTC m=+0.049302804] Loading modules...
[DEBUG][2022-01-31 22:21:49.25090657 +0000 UTC m=+0.049741527] Starting iteration 1 of context evaluation...
[DEBUG][2022-01-31 22:21:49.251394396 +0000 UTC m=+0.050229453] Starting iteration 2 of context evaluation...
[DEBUG][2022-01-31 22:21:49.252139235 +0000 UTC m=+0.050974292] Starting iteration 2 of context evaluation...
[DEBUG][2022-01-31 22:21:49.253069484 +0000 UTC m=+0.051904541] Module [azure-mssql-database:/agent/_work/1/s/.terraform/modules/azure-mssql-database:module.azure-mssql-database] has already been seen
[DEBUG][2022-01-31 22:21:49.253578811 +0000 UTC m=+0.052413868] Module [featurepreview-fa:/agent/_work/1/s/.terraform/modules/featurepreview-fa:module.featurepreview-fa] has already been seen
[DEBUG][2022-01-31 22:21:49.25413084 +0000 UTC m=+0.052965797] Module [featurepreview-appconfig[0]:/agent/_work/1/s/.terraform/modules/featurepreview-appconfig:module.featurepreview-appconfig] has already been seen
[DEBUG][2022-01-31 22:21:49.254801176 +0000 UTC m=+0.053636133] Starting iteration 3 of context evaluation...
[DEBUG][2022-01-31 22:21:49.25564672 +0000 UTC m=+0.054481777] Module [azure-mssql-database:/agent/_work/1/s/.terraform/modules/azure-mssql-database:module.azure-mssql-database] has already been seen
[DEBUG][2022-01-31 22:21:49.256226551 +0000 UTC m=+0.055061508] Module [featurepreview-fa:/agent/_work/1/s/.terraform/modules/featurepreview-fa:module.featurepreview-fa] has already been seen
[DEBUG][2022-01-31 22:21:49.25677148 +0000 UTC m=+0.055606537] Module [featurepreview-appconfig[0]:/agent/_work/1/s/.terraform/modules/featurepreview-appconfig:module.featurepreview-appconfig] has already been seen
[DEBUG][2022-01-31 22:21:49.257430315 +0000 UTC m=+0.056265272] Starting scanner...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x92e067]

goroutine 1 [running]:
github.com/aquasecurity/tfsec/internal/pkg/block.Ignore.Covering({{0xd13bd8, 0xc000369dc0}, {0xc0000304cd, 0x26}, 0xc000374bd0, {0x0, 0x0}, 0x0}, {{0x0, 0x0}, ...}, ...)
	/home/runner/work/tfsec/tfsec/internal/pkg/block/ignore.go:48 +0x187
github.com/aquasecurity/tfsec/internal/pkg/block.Ignores.Covering({0xc00004cc00, 0xa, 0xbd7589}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, 0x0, ...}, ...)
	/home/runner/work/tfsec/tfsec/internal/pkg/block/ignore.go:21 +0x19c
github.com/aquasecurity/tfsec/internal/pkg/scanner.(*Scanner).Scan(0xc0004ccf60, {0xc00052dd40, 0x0, 0x4})
	/home/runner/work/tfsec/tfsec/internal/pkg/scanner/scanner.go:78 +0x77f
github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.glob..func1(0x127a1c0, {0xc0002e9040, 0x1, 0x5})
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/cmd/root.go:114 +0x7ec
github.com/spf13/cobra.(*Command).execute(0x127a1c0, {0xc00001e1f0, 0x5, 0x5})
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x127a1c0)
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:902
main.main()
	/home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:11 +0x25
```

We also found that 1.0.2 failed for a different reason.

```
/agent/_work/_temp/69700cd5-b677-4a22-9bb2-ac9c30775123/tfsec-linux-amd64 --format=junit --out /agent/_work/_temp/f31fff1f-7f84-4bdf-8c98-e6665cc6662a.junit --include-passed --soft-fail  '/agent/_work/1/s'
panic: not a string

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.AsString({{{0x0, 0x0}}, {0x0, 0x0}})
	/home/runner/work/tfsec/tfsec/vendor/github.com/zclconf/go-cty/cty/value_ops.go:1256 +0x138
github.com/aquasecurity/tfsec/internal/pkg/adapter/azure/keyvault.adaptSecret(0xc00042c3c0)
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/azure/keyvault/adapt.go:113 +0x165
github.com/aquasecurity/tfsec/internal/pkg/adapter/azure/keyvault.(*adapter).adaptVaults(0xc0005bc100, {0xc0002c56e0, 0xbbca40, 0x4})
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/azure/keyvault/adapt.go:44 +0x347
github.com/aquasecurity/tfsec/internal/pkg/adapter/azure/keyvault.Adapt({0xc0002c56e0, 0x4, 0x4})
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/azure/keyvault/adapt.go:18 +0x11c
github.com/aquasecurity/tfsec/internal/pkg/adapter/azure.Adapt({_, _, _})
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/azure/adapt.go:30 +0x356
github.com/aquasecurity/tfsec/internal/pkg/adapter.Adapt({0xc0002c56e0, 0x4, 0x4})
	/home/runner/work/tfsec/tfsec/internal/pkg/adapter/adapt.go:20 +0x8c
github.com/aquasecurity/tfsec/internal/pkg/scanner.(*Scanner).Scan(0xc0003c4420, {0xc0002c56e0, 0x0, 0x4})
	/home/runner/work/tfsec/tfsec/internal/pkg/scanner/scanner.go:51 +0x9f
github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.glob..func1(0x127f080, {0xc000334660, 0x1, 0x6})
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/cmd/root.go:114 +0x7ec
github.com/spf13/cobra.(*Command).execute(0x127f080, {0xc00001e080, 0x6, 0x6})
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x127f080)
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:902
main.main()
	/home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:11 +0x25
```

**Expected behavior**
Runner should produce a result without failing. Previous version that worked was 0.63.1. 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by favoretti** [comment]
Same here:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x931c47]

goroutine 1 [running]:
github.com/aquasecurity/tfsec/internal/pkg/block.Ignore.Covering({{0xd19158, 0xc00189c580}, {0xc000b1cb31, 0x6}, 0x0, {0x0, 0x0}, 0x0}, {{0x0, 0x0}, ...}, ...)
	/home/runner/work/tfsec/tfsec/internal/pkg/block/ignore.go:48 +0x187
github.com/aquasecurity/tfsec/internal/pkg/block.Ignores.Covering({0xc000eb8000, 0xf, 0xbd9205}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, 0x0, ...}, ...)
	/home/runner/work/tfsec/tfsec/internal/pkg/block/ignore.go:21 +0x19c
github.com/aquasecurity/tfsec/internal/pkg/scanner.(*Scanner).Scan(0xc00d55be60, {0xc014194000, 0x0, 0x550})
	/home/runner/work/tfsec/tfsec/internal/pkg/scanner/scanner.go:78 +0x77f
github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.glob..func1(0x12801a0, {0xc0003c6720, 0x1, 0x6})
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/cmd/root.go:114 +0x7ec
github.com/spf13/cobra.(*Command).execute(0x12801a0, {0xc00001e080, 0x6, 0x6})
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x12801a0)
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:902
main.main()
	/home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:11 +0x25

```

I can run it in debug mode to help if you want?

**Comment by liamg** [comment]
Working on this, a fix should be available later today

**Comment by favoretti** [comment]
In my case it fails on old style of ignores, code contained `#tfsec:ignore:AZU001`

**Comment by liamg** [comment]
Thanks, `v1.0.8` is building now with this fix.
