### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by bdorplatt** [aquasecurity/tfsec#1711]
**Describe the bug**
When run against an Azure Storage Account, TFSec crashes pipeline with error referring to the default_action_deny check

**To Reproduce**
Run TFSec v1.19.1 against an Azure storage account. We are running in a pipeline using "/root/go/bin/tfsec --force-all-dirs"
Error detailed below is displayed.
This is occurring even after adding an ignore comment for the check:
#tfsec:ignore:azure-storage-default-action-deny

**Expected behavior**
TFSec runs and checks storage account resources and returns issues if present.

**Screenshots/Output**
Error: scan failed: job failed: runtime error: invalid memory address or nil pointer dereference
goroutine 187 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*infraRuleJob).Run.func1()
	/root/go/pkg/mod/github.com/aquasecurity/defsec@v0.46.3/pkg/scanners/terraform/executor/pool.go:128 +0x45
panic({0x11fe580, 0x203c560})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/aquasecurity/defsec/internal/rules/azure/storage.glob..func2(0xc000991c00)
	/root/go/pkg/mod/github.com/aquasecurity/defsec@v0.46.3/internal/rules/azure/storage/default_action_deny.go:37 +0x174
github.com/aquasecurity/defsec/internal/rules.RegisteredRule.Evaluate({0xab, {{0x1375473, 0xc}, {0x0, 0x0}, {0x138263f, 0x13}, {0x13e3287, 0x49}, {0x13f7a22, ...}, ...}, ...}, ...)
	/root/go/pkg/mod/github.com/aquasecurity/defsec@v0.46.3/internal/rules/register.go:26 +0x3b
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*infraRuleJob).Run(0x1340380)
	/root/go/pkg/mod/github.com/aquasecurity/defsec@v0.46.3/pkg/scanners/terraform/executor/pool.go:132 +0xf9
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Worker).Start.func1(0x0, 0xc0004dad40)
	/root/go/pkg/mod/github.com/aquasecurity/defsec@v0.46.3/pkg/scanners/terraform/executor/pool.go:274 +0x2a
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Worker).Start(0xc0004dad40)
	/root/go/pkg/mod/github.com/aquasecurity/defsec@v0.46.3/pkg/scanners/terraform/executor/pool.go:279 +0xb6
created by github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Pool).Run
	/root/go/pkg/mod/github.com/aquasecurity/defsec@v0.46.3/pkg/scanners/terraform/executor/pool.go:55 +0xef

##[error]Bash exited with code '1'.
Finishing: TFSec Static Code Analysis

**System Info**
 - tfsec version: 1.19.1
 - terraform version: 0.15.4 Provider version 3.4.0
 - OS: Ubuntu 20.04.4 LTS

**Example Code**
**Calling the module:**
#tfsec:ignore:azure-storage-default-action-deny
module "storage-account" {
  source              = "git::ssh://git@ssh.dev.azure.com/xxxxxx/terraform-azure-storageaccount?ref=v1.4"
  region                                      = var.region
  resource_group_name             = var.resource_group_name
  sa_allow_blob_public_access   = var.sa_allow_blob_public_access
  sa_kind                                     = var.sa_kind
  sa_name_short                         = var.sa_name_short
  sa_network_rules_default_action = var.sa_network_rules_default_action
  sa_replication_type                  = var.sa_replication_type
  sa_tier                                      = var.sa_tier
  subscription                            = var.subscription
  tenant                                     = var.tenant
}

**The module code:**
resource "azurerm_storage_account" "storage" {
  account_kind                                 = var.sa_kind
  account_replication_type              = var.sa_replication_type
  account_tier                                  = var.sa_tier
  allow_nested_items_to_be_public = var.sa_allow_blob_public_access
  location                                         = var.region
  name                                             = "${var.tenant}${var.subscription}${var.sa_name_short}sta"
  resource_group_name                  = var.resource_group_name

  network_rules {
    default_action                      =  var.sa_network_rules_default_action
    virtual_network_subnet_ids =  var.sa_virtual_network_subnet_ids
    ip_rules = [

    ]
  }
}

**Variable is set as follows:**
 sa_network_rules_default_action                   = "Allow"

**Additional context**
This seems to have started happening only after the latest TFSec update.

**Comment by bdorplatt** [comment]
We found a workaround where the env.hcl variables file can be parsed as part of the Terragrunt run. Calling TFSec using a before_hook as below in a top-level terragrunt.hcl file and runs tfsec prior to the Plan but after it has gathered the variables it needs:

terraform {
    before_hook "before_hook" {
    commands = ["plan"]
    execute  = ["/root/go/bin/tfsec", "."]
  }
}
