### ISSUE TITLE
bug: panic: value is unknown with >= v1.20.x

### ISSUE THREAD

**Issue by wyardley** [aquasecurity/tfsec#1731]
**Describe the bug**
With version 1.21, code that worked fine with 1.18 is giving me a panic with some of our states that use the GCP provider. It seems as if it's due to a reference from one module's output getting passed into another module.

Confirmed that 1.20.2 is also affected. Updating to 1.19.1 does not seem to exhibit the problem.

More code examples below.

**To Reproduce**
1. `tfsec foo`

**Expected behavior**
`tfsec` to run against the state

**Screenshots/Output**
```
panic: value is unknown

goroutine 1042 [running]:
github.com/zclconf/go-cty/cty.Value.AsString({{{0x279def0?, 0xc00018a0ea?}}, {0x216e9c0?, 0x339b2a0?}})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/value_ops.go:1262 +0x111
github.com/aquasecurity/defsec/pkg/terraform.(*Reference).KeyBracketed(0xc00171efc0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/terraform/reference.go:147 +0xa5
github.com/aquasecurity/defsec/pkg/terraform.(*Reference).String(0xc00171efc0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/terraform/reference.go:110 +0x165
github.com/aquasecurity/defsec/internal/types.(*Metadata).ToRego(0xc000e089e8)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/internal/types/metadata.go:27 +0x76
github.com/aquasecurity/defsec/pkg/rego/convert.StructToRego({0x22fc000?, 0xc0005ace70?, 0x21a5c00?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/struct.go:55 +0x5d5
github.com/aquasecurity/defsec/pkg/rego/convert.anonymousToRego({0x22fc000?, 0xc0005ace70?, 0x0?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/anonymous.go:34 +0x2a5
github.com/aquasecurity/defsec/pkg/rego/convert.StructToRego({0x22ed380?, 0xc000c84180?, 0x21a5c00?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/struct.go:41 +0x3b4
github.com/aquasecurity/defsec/pkg/rego/convert.anonymousToRego({0x22ed380?, 0xc000c84180?, 0x0?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/anonymous.go:34 +0x2a5
github.com/aquasecurity/defsec/pkg/rego/convert.SliceToRego({0x2100740?, 0xc000bb7038?, 0x21a5c00?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/slice.go:28 +0x24b
github.com/aquasecurity/defsec/pkg/rego/convert.anonymousToRego({0x2100740?, 0xc000bb7038?, 0x0?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/anonymous.go:36 +0x2db
github.com/aquasecurity/defsec/pkg/rego/convert.StructToRego({0x22ed500?, 0xc000330460?, 0x21a5c00?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/struct.go:41 +0x3b4
github.com/aquasecurity/defsec/pkg/rego/convert.anonymousToRego({0x22ed500?, 0xc000330460?, 0x0?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/anonymous.go:34 +0x2a5
github.com/aquasecurity/defsec/pkg/rego/convert.SliceToRego({0x21007c0?, 0xc000bb6c90?, 0x21a5c00?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/slice.go:28 +0x24b
github.com/aquasecurity/defsec/pkg/rego/convert.anonymousToRego({0x21007c0?, 0xc000bb6c90?, 0x0?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/anonymous.go:36 +0x2db
github.com/aquasecurity/defsec/pkg/rego/convert.StructToRego({0x22f4be0?, 0xc0016b2c30?, 0x21a5c00?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/struct.go:41 +0x3b4
github.com/aquasecurity/defsec/pkg/rego/convert.anonymousToRego({0x22f4be0?, 0xc0016b2c30?, 0x0?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/anonymous.go:34 +0x2a5
github.com/aquasecurity/defsec/pkg/rego/convert.SliceToRego({0x2100780?, 0xc000ed27e0?, 0x21a5c00?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/slice.go:28 +0x24b
github.com/aquasecurity/defsec/pkg/rego/convert.anonymousToRego({0x2100780?, 0xc000ed27e0?, 0x0?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/anonymous.go:36 +0x2db
github.com/aquasecurity/defsec/pkg/rego/convert.StructToRego({0x21c21c0?, 0xc000ed27e0?, 0x21a5c00?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/struct.go:41 +0x3b4
github.com/aquasecurity/defsec/pkg/rego/convert.anonymousToRego({0x21c21c0?, 0xc000ed27e0?, 0x0?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/anonymous.go:34 +0x2a5
github.com/aquasecurity/defsec/pkg/rego/convert.StructToRego({0x22bd640?, 0xc000ed26e0?, 0x21a5c00?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/struct.go:41 +0x3b4
github.com/aquasecurity/defsec/pkg/rego/convert.anonymousToRego({0x22bd640?, 0xc000ed26e0?, 0x0?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/anonymous.go:34 +0x2a5
github.com/aquasecurity/defsec/pkg/rego/convert.StructToRego({0x2169440?, 0xc0001dec00?, 0xc0019a0e48?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/rego/convert/struct.go:41 +0x3b4
github.com/aquasecurity/defsec/pkg/state.(*State).ToRego(0x100686b?)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/state/state.go:31 +0x9c
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*regoJob).Run(0xc00079ab80)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/scanners/terraform/executor/pool.go:162 +0x45
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Worker).Start.func1(0x0?, 0xc000b8d7c0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/scanners/terraform/executor/pool.go:281 +0x2a
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Worker).Start(0xc000b8d7c0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/scanners/terraform/executor/pool.go:286 +0xb6
created by github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Pool).Run
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.57.3/pkg/scanners/terraform/executor/pool.go:55 +0xea
rita~/git/terraform(wyardley/ci/update-versions|✔)% 
```

**System Info**

 - tfsec version: `v1.21.0`
 - terraform version: `v1.1.9`
 - OS: `darwin_amd64`

**Example Code**
```hcl
# test.tf
module "module1" {
  source  = "../modules/module1"
}

module "module2" {
  source       = "../modules/module2"
  project      = var.project
  custom_roles = [module.module1.cache_invalidation_role_id]
}
# variables.tf
variable "project" {
  description = "Project to use for IAM roles"
  type        = string
  default     = "foo"
}
```

simplified version of `module1`:
```hcl
# main.tf
resource "google_project_iam_custom_role" "cache_invalidation" {
  role_id     = "customCacheInvalidation"
  title       = "Cache Invalidation Custom Role"
  description = "Custom role for cache invalidation"
  permissions = ["compute.urlMaps.invalidateCache"]
}
# outputs.tf
output "cache_invalidation_role_id" {
  description = "ID for custom cache invalidation role"
  value       = google_project_iam_custom_role.cache_invalidation.id
}
```

**Additional context**
simplified version of module2:
```hcl
## variables.tf
variable "username" {
  description = "Username to create"
  type        = string
  default     = "testuser"
}

variable "display_name" {
  description = "Display name for user"
  type        = string
  default     = "foo user"
}

variable "project" {
  description = "Project to use for IAM roles"
  type        = string
}

variable "roles" {
  description = "List of roles to grant user"
  type        = list(string)
  default = [
    "roles/compute.viewer",
    "roles/storage.objectAdmin"
  ]
}

variable "custom_roles" {
  description = "Pass in additional custom roles to append (e.g., cache invalidation)"
  type        = list(string)
  default     = []
}

## main.tf
locals {
  roles = toset(concat(var.roles, var.custom_roles))
}

resource "google_service_account" "foo" {
  account_id   = var.username
  display_name = var.display_name
}

resource "google_project_iam_member" "role" {
  for_each = local.roles
  role     = each.value
  project  = var.project
  member   = "serviceAccount:${google_service_account.foo.email}"
}
```

This normally runs in CI, but initializing the state and / or running `terraform refresh` doesn't fix the problem locally.

**Comment by tommy31** [comment]
Same here. 
Seems that requesting local module in a local module throw this error.

**Comment by wyardley** [comment]
Oddly, not only does my simple repro case not work if I recreate it from scratch, but if I _literally_ copy the same entire directory that's crashing into another directory outside of my working directory, and update the module paths (still pointing to the same modules), `tfsec` now runs without error. If I remove the reference from the output of one module in another, it also works. I've tried removing the `.tfsec` cache dir (and the error is reproducible in CI, so I don't think it's just something in my local env). But if (in the same directory), I replace that module reference with any random (but unquoted) string, the crash happens as well.

Not sure if this helps, but happy to try to debug more if it would help. The stack trace looks the same as the one printed, but happy to run some commands in Delve off a debug build if it would help.

**Comment by wyardley** [comment]
I can repro more or less the same issue by putting any invalid string in the module resource reference, so maybe it's an issue with following that reference in certain cases?
