### ISSUE TITLE
bug: tfsec panic on latest version

### ISSUE THREAD

**Issue by Lethgir** [aquasecurity/tfsec#1862]
**Describe the bug**
Since version 1.27.2 I encounter a panic on my project when I execute tfsec

**To Reproduce**
1. Execute `tsec`

**Expected behavior**
No panic error (or maybe a more explicit error)

**Output of your tfsec command with --debug flag**
```
tfsec --debug
42:41.542756345 system.info                      APP       tfsec
42:41.542778775 system.info                      VERSION   v1.27.2
42:41.542780254 system.info                      OS        linux
42:41.542781443 system.info                      ARCH      amd64
42:41.542784240 system.info                      KERNEL    Linux version 5.18.10-76051810-generic (jenkins@warp.pop-os.org) (gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #202207071639~1659403207~22.04~cb5f582 SMP PREEMPT_DYNAMIC Tue A
42:41.542787132 system.info                      TERM      xterm-256color
42:41.542789389 system.info                      SHELL     /bin/bash
42:41.542790649 system.info                      GOVERSION go1.18.5
42:41.542793827 system.info                      GOROOT    /opt/hostedtoolcache/go/1.18.5/x64
42:41.542796041 system.info                      CGO       false
42:41.542797656 system.info                      CPUCOUNT  12
42:41.542799044 system.info                      MAXPROCS  12
42:41.542800817 system.info                      WORKDIR   /REDACTED
42:41.542803122 system.info                      UID       1000
42:41.542805271 system.info                      EUID      1000
42:41.542807139 system.info                      DOCKER    false
42:41.542809000 system.info                      CI        false
42:41.542810287 system.info                      HOSTNAME  pop-os
42:41.542812551 system.info                      TEMP      /tmp
42:41.542814958 system.info                      PATHSEP   /
42:41.542817103 system.info                      CMD       tfsec --debug
42:41.542819722 cmd                              Command args=[]string{}
42:41.542824983 cmd                              Determined path dir=/REDACTED
42:41.542864060 cmd                              Determined path root=/
42:41.542866820 cmd                              Determined path rel=REDACTED
42:41.542888164 terraform.scanner                Scanning [&{/ /}] at 'REDACTED'...
42:41.553260673 terraform.scanner.rego           Loaded 4 embedded libraries.
42:41.572871745 terraform.scanner.rego           Loaded 116 embedded policies.
[...]
42:41.693934233 terraform.parser.<root>          Setting project/module root to 'REDACTED'
42:41.693936628 terraform.parser.<root>          Parsing FS from 'REDACTED'
42:41.694031442 terraform.parser.<root>          Parsing 'REDACTED'...
42:41.694305774 terraform.parser.<root>          Added file REDACTED.
[...]
42:41.725598641 terraform.parser.<root>          Evaluating module...
42:41.749691104 terraform.parser.<root>          Read 490 block(s) and 0 ignore(s) for module 'root' (32 file[s])...
42:41.749717404 terraform.parser.<root>          Added 1 variables from tfvars.
42:41.750145322 terraform.parser.<root>          Loaded module metadata for 313 module(s) from 'REDACTED'.
42:41.750155174 terraform.parser.<root>          Working directory for module evaluation is '/REDACTED'
42:41.750277706 terraform.parser.<root>.evaluator Filesystem key is 'REDACTED'
42:41.750282528 terraform.parser.<root>.evaluator Starting module evaluation...
42:41.758487538 terraform.parser.<root>.evaluator Expanded block 'REDACTED' into 1 clones via 'count' attribute.
[...]
42:41.760151108 terraform.parser.<root>.evaluator Expanded block 'REDACTED' into 1 clones via 'for_each' attribute.
42:41.760235199 terraform.parser.<root>.evaluator Starting submodule evaluation...
[...]
42:43.504750905 terraform.parser.<root>.evaluator Finished processing 238 submodule(s).
42:43.504753346 terraform.parser.<root>.evaluator Starting post-submodule evaluation...
42:43.511996824 terraform.parser.<root>.evaluator Module evaluation complete.
42:43.512032942 terraform.parser.<root>          Finished parsing module 'root'.
42:43.512040519 terraform.parser.<root>.evaluator Added module output REDACTED=cty.NilVal.
[...]
42:43.512193290 terraform.executor               Adapting modules...
panic: wow

goroutine 1 [running]:
github.com/aquasecurity/defsec/internal/adapters/terraform/aws/sqs.(*adapter).adaptQueues(0xc00d68aa80)
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/internal/adapters/terraform/aws/sqs/adapt.go:67 +0x139f
github.com/aquasecurity/defsec/internal/adapters/terraform/aws/sqs.Adapt(...)
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/internal/adapters/terraform/aws/sqs/adapt.go:19
github.com/aquasecurity/defsec/internal/adapters/terraform/aws.Adapt({_, _, _})
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/internal/adapters/terraform/aws/adapt.go:71 +0xafd
github.com/aquasecurity/defsec/internal/adapters/terraform.Adapt({0xc00a01b800, 0xef, 0x100})
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/internal/adapters/terraform/adapt.go:19 +0x4e
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Executor).Execute(0xc000d50000, {0xc00a01b800?, 0xef, 0x100})
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/pkg/scanners/terraform/executor/executor.go:96 +0x11a
github.com/aquasecurity/defsec/pkg/scanners/terraform.(*Scanner).ScanFSWithMetrics(0xc0002364b0, {0x1e36f68, 0xc00003e110}, {0x7fc3da2a7110?, 0xc000e216e0?}, {0xc000044125, 0x27})
	/home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/pkg/scanners/terraform/scanner.go:210 +0x6b1
github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.Root.func1(0xc000307680, {0xc0007700e0, 0x0, 0x1})
	/home/runner/work/tfsec/tfsec/internal/app/tfsec/cmd/root.go:83 +0x633
github.com/spf13/cobra.(*Command).execute(0xc000307680, {0xc00003a030, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000307680)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
	/home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:12 +0x25
```

**System Info**

 - tfsec version: `1.27.2`
 - terraform version: `1.2.5`
 - OS: `POP OS 22.04`

**Additional context**
It seems to be related to a specific module because when I remove it, the analysis is well executed. However, when I execute the analysis only on this submodule, I don't get a panic error.

The given module declaration looks like this:
```hcl
module "events" {
  source = "../../modules/sqs-queue/"

  name = "${local.mylocalvar}--events"

  enable_sns_subscription     = true
  sns_subscriptions_topic_arn = var.var1
  cost_component              = local.mylocalvar
  max_message_size            = local.mylocalvar2
  message_retention_seconds   = local.mylocalvar3
  visibility_timeout_seconds  = 70
  alarms_sns_topic_arn        = var.var2
}
```
It also has two outputs used inside the root module.

**Comment by gerbenoostra** [comment]
On `tfsec` version 1.27.2 I'm getting a similar panic, but slightly different error message:
```
50:18.331068000 terraform.executor               Adapting modules...
panic: value is unknown

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.AsString({{{0x2a78010?, 0xc0001a2359?}}, {0x22ae2c0?, 0x3779ba0?}})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/value_ops.go:1262 +0x111
github.com/aquasecurity/defsec/pkg/terraform.(*Reference).Key(0xc0025c7ef0)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/pkg/terraform/reference.go:166 +0x9e
github.com/aquasecurity/defsec/pkg/terraform.(*Reference).RefersTo(0xc0025c7ef0, {0x2a743c0?, 0xc0022e4360})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/pkg/terraform/reference.go:131 +0x1f7
github.com/aquasecurity/defsec/pkg/terraform.(*Attribute).ReferencesBlock(0xc001cf57c0?, 0xc00222d8c0)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/pkg/terraform/attribute.go:822 +0xe7
github.com/aquasecurity/defsec/internal/adapters/terraform/aws/iam.mapUsers({0xc0021e0700, 0x10, 0x10})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/internal/adapters/terraform/aws/iam/users.go:128 +0x727
github.com/aquasecurity/defsec/internal/adapters/terraform/aws/iam.adaptUsers({0xc0021e0700, 0x10, 0x10})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/internal/adapters/terraform/aws/iam/users.go:11 +0x46
github.com/aquasecurity/defsec/internal/adapters/terraform/aws/iam.Adapt({_, _, _})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/internal/adapters/terraform/aws/iam/adapt.go:13 +0x11a
github.com/aquasecurity/defsec/internal/adapters/terraform/aws.Adapt({_, _, _})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/internal/adapters/terraform/aws/adapt.go:60 +0x68c
github.com/aquasecurity/defsec/internal/adapters/terraform.Adapt({0xc0021e0700, 0x10, 0x10})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/internal/adapters/terraform/adapt.go:19 +0x4e
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Executor).Execute(0xc0009b8100, {0xc0021e0700?, 0x10, 0x10})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/pkg/scanners/terraform/executor/executor.go:96 +0x11a
github.com/aquasecurity/defsec/pkg/scanners/terraform.(*Scanner).ScanFSWithMetrics(0xc0002b41e0, {0x2a76aa0, 0xc0001a2030}, {0xbf4bb78?, 0xc000f1aac0?}, {0xc00004a105, 0x2c})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.72.0/pkg/scanners/terraform/scanner.go:210 +0x6b6
github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.Root.func1(0xc00025d400, {0xc0016fd4b0, 0x0, 0x1})
        /private/tmp/tfsec-20220819-4070-1a8l2pj/tfsec-1.27.2/internal/app/tfsec/cmd/root.go:83 +0x632
github.com/spf13/cobra.(*Command).execute(0xc00025d400, {0xc0001aa010, 0x1, 0x1})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc00025d400)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /private/tmp/tfsec-20220819-4070-1a8l2pj/tfsec-1.27.2/cmd/tfsec/main.go:12 +0x25
```

**Comment by commarla** [comment]
Hi, I am working with @Lethgir and I have more info.

The module we source is the following:

```
resource "aws_sqs_queue_policy" "sns_queue" {
  count = var.enable_sns_subscription ? 1 : 0

  queue_url = aws_sqs_queue.this.id
  policy    = data.aws_iam_policy_document.sns[0].json
}

resource "aws_sqs_queue_policy" "sns_dlq" {
  count = var.enable_sns_subscription ? 1 : 0

  queue_url = aws_sqs_queue.dlq.id
  policy    = data.aws_iam_policy_document.sns[0].json
}

data "aws_iam_policy_document" "sns" {
  count = var.enable_sns_subscription ? 1 : 0

  statement {
    effect = "Allow"
    principals {
      type        = "Service"
      identifiers = ["sns.amazonaws.com"]
    }
    actions = ["sqs:SendMessage"]
    resources = [
      aws_sqs_queue.this.arn,
    ]

    condition {
      test     = "ArnEquals"
      variable = "aws:SourceArn"
      values   = [var.sns_subscriptions_topic_arn]
    }
  }
}

resource "aws_sqs_queue" "this" {
  content_based_deduplication = var.content_based_deduplication
  delay_seconds               = var.delay_seconds
  fifo_queue                  = var.fifo
  kms_master_key_id           = data.aws_kms_key.this.id
  max_message_size            = var.max_message_size
  message_retention_seconds   = var.message_retention_seconds
  name                        = local.queue_name
  receive_wait_time_seconds   = var.receive_wait_time_seconds
  visibility_timeout_seconds  = var.visibility_timeout_seconds

  redrive_policy = <<EOF
{
  "deadLetterTargetArn": "${aws_sqs_queue.dlq.arn}",
  "maxReceiveCount": ${var.max_receive_count}
}
EOF

  tags = local.module_tags,
}

resource "aws_sqs_queue" "dlq" {
  fifo_queue                 = var.fifo
  kms_master_key_id          = data.aws_kms_key.this.id
  max_message_size           = var.max_message_size
  message_retention_seconds  = 1209600 # 14 days
  name                       = local.dlq_name
  visibility_timeout_seconds = var.visibility_timeout_seconds
  tags = local.module_tags
}
```

The `panic` disappears if I remove the `count` on the 2 `aws_sqs_queue_policy` resources. Or if I comment out the `enable_sns_subscription     = true` in the module declaration

**Comment by liamg** [comment]
Thanks, fix incoming (10 minutes)
