### ISSUE TITLE
bug: tfsec failing to run (invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by blaqguy** [aquasecurity/tfsec#1894]
**Describe the bug**
tfsec version 1.27.6 is failing to run against Terraform CDK cdk.tf.json file. This is the full error I'm getting:  
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x107178c]

goroutine 1 [running]:
github.com/aquasecurity/defsec/pkg/terraform.(*Block).GetMetadata(...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/pkg/terraform/block.go:129
github.com/aquasecurity/defsec/internal/adapters/terraform/aws/s3.isEncrypted(0xc00017afc0?)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/internal/adapters/terraform/aws/s3/bucket.go:208 +0x8c
github.com/aquasecurity/defsec/internal/adapters/terraform/aws/s3.getEncryption(0xc00017afc0, 0xc0015a0750)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/internal/adapters/terraform/aws/s3/bucket.go:44 +0x9ea
github.com/aquasecurity/defsec/internal/adapters/terraform/aws/s3.(*adapter).adaptBuckets(0xc0015a0750)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/internal/adapters/terraform/aws/s3/bucket.go:21 +0x14b
github.com/aquasecurity/defsec/internal/adapters/terraform/aws/s3.Adapt(...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/internal/adapters/terraform/aws/s3/adapt.go:16
github.com/aquasecurity/defsec/internal/adapters/terraform/aws.Adapt({_, _, _})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/internal/adapters/terraform/aws/adapt.go:69 +0x9fd
github.com/aquasecurity/defsec/internal/adapters/terraform.Adapt({0xc0003aad90, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/internal/adapters/terraform/adapt.go:19 +0x4e
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Executor).Execute(0xc000998300, {0xc0003aad90?, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/pkg/scanners/terraform/executor/executor.go:96 +0x11a
github.com/aquasecurity/defsec/pkg/scanners/terraform.(*Scanner).ScanFSWithMetrics(0xc0002204b0, {0x1e44f40, 0xc00003c0d0}, {0x7f88bdedf350?, 0xc0003c6f40?}, {0xc000042095, 0x2b})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/pkg/scanners/terraform/scanner.go:210 +0x75a
github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.Root.func1(0xc0003e6a00, {0x2b1cc18, 0x0, 0x0})
        /home/runner/work/tfsec/tfsec/internal/app/tfsec/cmd/root.go:83 +0x633
github.com/spf13/cobra.(*Command).execute(0xc0003e6a00, {0xc00003a220, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003e6a00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:12 +0x25
```

**To Reproduce**
1. Create a cdktf project
2. Write some code and run cdktf synth
3. Run tfsec in the cdktf project directory

**Expected behavior**
I was expecting tfsec to run successfully.

**Output of your tfsec command with --debug flag**
```
32:29.800083000 system.info                      APP       tfsec
32:29.800405400 system.info                      VERSION   v1.27.6
32:29.800409100 system.info                      OS        linux
32:29.800410700 system.info                      ARCH      amd64
32:29.800430600 system.info                      KERNEL    Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Fri Apr 2 22:23:49 UTC 2021
32:29.800439000 system.info                      TERM      xterm-256color
32:29.800444100 system.info                      SHELL     /usr/bin/zsh
32:29.800447000 system.info                      GOVERSION go1.18.5
32:29.800451600 system.info                      GOROOT    /opt/hostedtoolcache/go/1.18.5/x64
32:29.800486100 system.info                      CGO       false
32:29.800512600 system.info                      CPUCOUNT  12
32:29.800563300 system.info                      MAXPROCS  12
32:29.800601200 system.info                      WORKDIR   /mnt/c/Users/Castle/Desktop/cdkTF/cdktf-eval
32:29.800605800 system.info                      UID       1000
32:29.800622500 system.info                      EUID      1000
32:29.800624100 system.info                      DOCKER    false
32:29.800626100 system.info                      CI        false
32:29.800627700 system.info                      HOSTNAME  DESKTOP-9S2VLJU
32:29.800629400 system.info                      TEMP      /tmp
32:29.800648700 system.info                      PATHSEP   /
32:29.800650700 system.info                      CMD       tfsec --debug
32:29.800656100 cmd                              Command args=[]string{}
32:29.801796700 cmd                              Determined path dir=/mnt/c/Users/Castle/Desktop/cdkTF/cdktf-eval
32:29.804555100 cmd                              Determined path root=/
32:29.804600400 cmd                              Determined path rel=mnt/c/Users/Castle/Desktop/cdkTF/cdktf-eval
32:29.805868800 terraform.scanner                Scanning [&{/ /}] at 'mnt/c/Users/Castle/Desktop/cdkTF/cdktf-eval'...
32:35.829325600 terraform.scanner.rego           Loaded 4 embedded libraries.
32:35.857558200 terraform.scanner.rego           Loaded 116 embedded policies.
32:35.947673300 terraform.scanner                Scanning root module 'mnt/c/Users/Castle/Desktop/cdkTF/cdktf-eval/cdktf.out/stacks/cdktf-eval'...
32:35.947757600 terraform.parser.<root>          Setting project/module root to 'mnt/c/Users/Castle/Desktop/cdkTF/cdktf-eval/cdktf.out/stacks/cdktf-eval'
32:35.947762300 terraform.parser.<root>          Parsing FS from 'mnt/c/Users/Castle/Desktop/cdkTF/cdktf-eval/cdktf.out/stacks/cdktf-eval'
32:35.953470300 terraform.parser.<root>          Parsing 'mnt/c/Users/Castle/Desktop/cdkTF/cdktf-eval/cdktf.out/stacks/cdktf-eval/cdk.tf.json'...
32:35.961097100 terraform.parser.<root>          Added file mnt/c/Users/Castle/Desktop/cdkTF/cdktf-eval/cdktf.out/stacks/cdktf-eval/cdk.tf.json.
32:35.962712500 terraform.parser.<root>          Evaluating module...
32:35.963619700 terraform.parser.<root>          Read 10 block(s) and 0 ignore(s) for module 'root' (1 file[s])...
32:35.963736500 terraform.parser.<root>          Added 0 variables from tfvars.
32:35.966992100 terraform.parser.<root>          Error loading module metadata: open //mnt/c/Users/Castle/Desktop/cdkTF/cdktf-eval/cdktf.out/stacks/cdktf-eval/.terraform/modules/modules.json: no such file or directory.      
32:35.967718500 terraform.parser.<root>          Working directory for module evaluation is '/mnt/c/Users/Castle/Desktop/cdkTF/cdktf-eval'
32:35.967989600 terraform.parser.<root>.evaluator Filesystem key is 'f9088d3ed2db9899500f703a07bb505300c2b5cbc122ac4365ca04af35422e64'
32:35.968019700 terraform.parser.<root>.evaluator Starting module evaluation...
32:35.970171600 terraform.parser.<root>.evaluator Starting submodule evaluation...
32:35.970226800 terraform.parser.<root>.evaluator Finished processing 0 submodule(s).
32:35.970231500 terraform.parser.<root>.evaluator Starting post-submodule evaluation...
32:35.971157200 terraform.parser.<root>.evaluator Module evaluation complete.
32:35.971255200 terraform.parser.<root>          Finished parsing module 'root'.
32:35.971288700 terraform.parser.<root>.evaluator Added module output tfBackend_bucket_4FB869C0=cty.StringVal("13184cc8-3821-4c3f-af9b-feaabb22bae9").
32:35.971365100 terraform.parser.<root>.evaluator Added module output tfBackend_key_id_057987E4=cty.StringVal("efa6b09e-21b4-4198-b213-61e34bbcba5e").
32:35.971532000 terraform.parser.<root>.evaluator Added module output tfBackend_table_289B9B8E=cty.StringVal("terraform-backend-lock").
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/internal/adapters/terraform/aws/s3/bucket.go:44 +0x9ea
github.com/aquasecurity/defsec/internal/adapters/terraform/aws/s3.(*adapter).adaptBuckets(0xc001066750)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/internal/adapters/terraform/aws/s3/bucket.go:21 +0x14bgithub.com/aquasecurity/defsec/internal/adapters/terraform/aws/s3.Adapt(...)        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/internal/adapters/terraform/aws/s3/adapt.go:16github.com/aquasecurity/defsec/internal/adapters/terraform/aws.Adapt({_, _, _})        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/internal/adapters/terraform/aws/adapt.go:69 +0x9fdgithub.com/aquasecurity/defsec/internal/adapters/terraform.Adapt({0xc0013779f0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/internal/adapters/terraform/adapt.go:19 +0x4egithub.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Executor).Execute(0xc001a02400, {0xc0013779f0?, 0x1, 0x1})        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/pkg/scanners/terraform/executor/executor.go:96 +0x11a
github.com/aquasecurity/defsec/pkg/scanners/terraform.(*Scanner).ScanFSWithMetrics(0xc0001fc4b0, {0x1e44f40, 0xc00003c0d0}, {0x7f3ed251f950?, 0xc000fa6400?}, {0xc000042095, 0x2b})        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.73.0/pkg/scanners/terraform/scanner.go:210 +0x75agithub.com/aquasecurity/tfsec/internal/app/tfsec/cmd.Root.func1(0xc0004ecc80, {0xc00074e460, 0x0, 0x1})
        /home/runner/work/tfsec/tfsec/internal/app/tfsec/cmd/root.go:83 +0x633github.com/spf13/cobra.(*Command).execute(0xc0004ecc80, {0xc00003a050, 0x1, 0x1})        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694github.com/spf13/cobra.(*Command).ExecuteC(0xc0004ecc80)        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()        /home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:12 +0x25
```
**System Info**

 - tfsec version: 1.27.6
 - terraform version: 1.2.9
 - OS: Ubuntu
**Example Code**
```
import { Construct } from "constructs";
import { App, TerraformStack, TerraformOutput } from "cdktf";
import { AwsProvider } from "@cdktf/provider-aws";
import { KmsKey, KmsAlias } from "@cdktf/provider-aws/lib/kms";
import { S3Bucket, S3BucketPublicAccessBlock } from "@cdktf/provider-aws/lib/s3";
import { DynamodbTable } from "@cdktf/provider-aws/lib/dynamodb";

export class tfBackend extends Construct {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    // Create KMS Key
    const terraformKey = new KmsKey(this, "TerraformBackendKey", {
      description: "Terraform Backend Key",
      deletionWindowInDays: 7,
      enableKeyRotation: true,
    });

    new KmsAlias(this, "TerraformBackendAlias", {
      name: "alias/terraform-backend-key",
      targetKeyId: terraformKey.id,
    });
    // Create S3 Bucket
    const terraformBucket = new S3Bucket(this, "TerraformBackendBucket", {
      acl: "private",
      versioning: {
        enabled: true,
        mfaDelete: false,
      },
      serverSideEncryptionConfiguration: {
        rule: {
          applyServerSideEncryptionByDefault: {
            sseAlgorithm: "aws:kms",
            kmsMasterKeyId: terraformKey.arn,
          },
        },
      },
    });
    
    new S3BucketPublicAccessBlock(this, "TerraformBackendBucketPublicAccessBlock", {
      bucket: terraformBucket.id,
      blockPublicAcls: true,
      blockPublicPolicy: true,
      ignorePublicAcls: true,
      restrictPublicBuckets: true,
    });
    // Create the DynamoDB table
    const terraformLock = new DynamodbTable(this, "TerraformBackendLock", {
      name: "terraform-backend-lock",
      billingMode: "PAY_PER_REQUEST",
      hashKey: "LockID",
      attribute: [
        {
          name: "LockID",
          type: "S",
        },
      ],
    });    
    // Output the bucket name
    new TerraformOutput(this, "bucket", {
      value: terraformBucket.id,
    });
    // Output the table name
    new TerraformOutput(this, "table", {
      value: terraformLock.name,
    });
    // Output the Key ID
    new TerraformOutput(this, "key_id", {
      value: terraformKey.id,
    });    
  }
}


// Deploy Resources
class MyStack extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    // define resources here
    new AwsProvider(this, "Aws", {
      region: "us-east-1",
    });
    new tfBackend(this, "tfBackend");
  }
}

const app = new App();
new MyStack(app, "cdktf-eval");
app.synth();
```

**Additional context**
This is also a problem on Windows 11.  Downgrading to v1.2.0 works.

**Comment by nikpivkin** [comment]
Hi @blaqguy !

I created the [issue](https://github.com/aquasecurity/trivy/issues/5080) in Trivy.

/cc @simar7
