### ISSUE TITLE
bug: module "gcs_buckets" tfsec panic: value is unknown

### ISSUE THREAD

**Issue by bruno-novo-freshbooks** [aquasecurity/tfsec#1926]
**Describe the bug**
Trying to execute tfsec in a resource already created(gcs_bucket)  but facing a weird error: `panic: value is unknown`

[terraform-google-cloud-storage](https://github.com/terraform-google-modules/terraform-google-cloud-storage/tree/v3.4.0)

**To Reproduce**
1. Create the resource
2. Try to run: tfsec .
3. The set_admin_roles flag is the problem. If leaved commented, there is no problem but the resource will be destroyed if already create and tfsec . run will pass. If leave uncommented, there will be no changes but tfsec fail's

**Expected behavior**
No problems detected!

**Output of your tfsec command with --debug flag**
```
panic: value is unknown

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.AsString({{{0x2ab9590?, 0xc0000c6359?}}, {0x22d4e20?, 0x37d4ce0?}})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/value_ops.go:1262 +0x111
github.com/aquasecurity/defsec/pkg/terraform.(*Reference).Key(0xc001cf99e0)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/pkg/terraform/reference.go:166 +0x9e
github.com/aquasecurity/defsec/pkg/terraform.(*Reference).RefersTo(0xc001cf99e0, {0x2ab5938?, 0xc000e92ab0})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/pkg/terraform/reference.go:131 +0x1f7
github.com/aquasecurity/defsec/pkg/terraform.(*Module).GetReferencedBlock(0xc001ae0fc0, 0xc001ade230, 0xc001ace480)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/pkg/terraform/module.go:123 +0x248
github.com/aquasecurity/defsec/pkg/terraform.Modules.GetReferencedBlock({0xc00186b7c0, 0x9, 0x2ab5938?}, 0xc000ec9170?, 0xc001ace480)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/pkg/terraform/modules.go:49 +0x70
github.com/aquasecurity/defsec/internal/adapters/terraform/google/storage.(*adapter).adaptBindings(0xc001e1ad60)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/internal/adapters/terraform/google/storage/iam.go:64 +0x5fd
github.com/aquasecurity/defsec/internal/adapters/terraform/google/storage.(*adapter).adaptBuckets(0xc001e1ad60)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/internal/adapters/terraform/google/storage/adapt.go:29 +0x157
github.com/aquasecurity/defsec/internal/adapters/terraform/google/storage.Adapt(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/internal/adapters/terraform/google/storage/adapt.go:11
github.com/aquasecurity/defsec/internal/adapters/terraform/google.Adapt({_, _, _})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/internal/adapters/terraform/google/adapt.go:25 +0x350
github.com/aquasecurity/defsec/internal/adapters/terraform.Adapt({0xc00186b7c0, 0x9, 0xa})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/internal/adapters/terraform/adapt.go:24 +0x205
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Executor).Execute(0xc000942400, {0xc00186b7c0?, 0x9, 0xa})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/pkg/scanners/terraform/executor/executor.go:96 +0x11a
github.com/aquasecurity/defsec/pkg/scanners/terraform.(*Scanner).ScanFSWithMetrics(0xc0002542d0, {0x2ab8020, 0xc0000c6030}, {0x9f16958?, 0xc0000edac0?}, {0xc00157c381, 0x3c})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/aquasecurity/defsec@v0.76.0/pkg/scanners/terraform/scanner.go:210 +0x776
github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.Root.func1(0xc0003d8c80, {0xc000fc6510, 0x1, 0x3})
        /private/tmp/tfsec-20220921-4406-bicg1v/tfsec-1.28.0/internal/app/tfsec/cmd/root.go:83 +0x632
github.com/spf13/cobra.(*Command).execute(0xc0003d8c80, {0xc0000c4050, 0x3, 0x3})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003d8c80)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /private/tmp/tfsec-20220921-4406-bicg1v/tfsec-1.28.0/cmd/tfsec/main.go:12 +0x25
```

**System Info**
 - tfsec version: `v1.28.0`
 - terraform version: `v1.3.1`
 - OS: `darwin_amd64` `Ubuntu`

**Example Code**
```
locals {
  app         = "my-application"
  sa_email = "test@YOUR-GCP_PROJECT.iam.gserviceaccount.com"
  common_tags = {
    "test"    = local.app,
  }
}
```

```
module "gcs_buckets" {
  source = "terraform-google-modules/cloud-storage/google"

  project_id      = var.project
  names           = ["${var.project}-${local.app}-my-bucket"]
  prefix          = ""
  location        = "US"
  labels          = local.common_tags
  admins          = ["serviceAccount:${local.sa_email}"]
  set_admin_roles = true # THE PROBLEM IS THIS SPECIFIC FLAG
} 
```

**Additional context**
Is just for this specific resource and this specific flag `set_admin_roles = true`

**Comment by bruno-novo-freshbooks** [comment]
Any thoughts?

**Comment by bruno-novo-freshbooks** [comment]
.

**Comment by bruno-novo-freshbooks** [comment]
,

**Comment by nikpivkin** [comment]
Hi @bruno-novo-freshbooks !

I opened the [issue](https://github.com/aquasecurity/trivy/issues/4983) in Trivy.

/cc @simar7
