### ISSUE TITLE
bug: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by JasonCubic** [aquasecurity/tfsec#1967]
**Describe the bug**

When I run tfsec on a terraform json file generated by CDKTF it throws the error: `panic: runtime error: invalid memory address or nil pointer dereference`  

The code in question is a cdktf version of this terraform azure hub and spoke tutorial all in one cdktf stack: https://learn.microsoft.com/en-us/azure/developer/terraform/hub-spoke-introduction

**To Reproduce**

1. clone this repo: https://github.com/JasonCubic/cdktf-az-hub-spoke-demo
2. do an npm install
3. run a cdktf synth
4. run tfsec on the folder ./cdktf.out/stacks/single-sub-hub-and-spoke
5. `tfsec ./cdktf.out/stacks/single-sub-hub-and-spoke`

**Expected behavior**

it should complete without the "invalid memory address or nil pointer dereference" error.

Similar to what happens when you run tfsec on this stack from the project: `tfsec ./cdktf.out/stacks/cdktf-demo`

**Output of your tfsec command with --debug flag**

```bash
docker run --rm -it -v "./cdktf.out/stacks/single-sub-hub-and-spoke:/src" docker.io/aquasec/tfsec /src --debug

45:13.531918491 system.info                      APP       tfsec
45:13.531942394 system.info                      VERSION   v1.28.1
45:13.531943664 system.info                      OS        linux
45:13.531944549 system.info                      ARCH      amd64
45:13.531945419 system.info                      KERNEL    Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Mar 2 00:30:59 UTC 2022
45:13.531947053 system.info                      TERM      xterm
45:13.531991349 system.info                      SHELL
45:13.531992645 system.info                      GOVERSION go1.18.7
45:13.531993839 system.info                      GOROOT    /opt/hostedtoolcache/go/1.18.7/x64
45:13.531995310 system.info                      CGO       false
45:13.531996621 system.info                      CPUCOUNT  20
45:13.531997617 system.info                      MAXPROCS  20
45:13.531998502 system.info                      WORKDIR   /
45:13.531999727 system.info                      UID       1000
45:13.532000813 system.info                      EUID      1000
45:13.532001625 system.info                      DOCKER    false
45:13.532002452 system.info                      CI        false
45:13.532003666 system.info                      HOSTNAME  7abdb71e8777
45:13.532004540 system.info                      TEMP      /tmp
45:13.532005481 system.info                      PATHSEP   /
45:13.532006689 system.info                      CMD       tfsec /src --debug
45:13.532009930 cmd                              Command args=[]string{"/src"}
45:13.532504257 cmd                              Determined path dir=/src
45:13.534187402 cmd                              Determined path root=/
45:13.534200865 cmd                              Determined path rel=src
45:13.534712748 terraform.scanner                Scanning [&{/ /}] at 'src'...
45:13.537919886 terraform.scanner.rego           Loaded 3 embedded libraries.
45:13.551682985 terraform.scanner.rego           Loaded 119 embedded policies.
45:13.639715768 terraform.scanner                Scanning root module 'src'...
45:13.639746343 terraform.parser.<root>          Setting project/module root to 'src'
45:13.639757734 terraform.parser.<root>          Parsing FS from 'src'
45:13.641258901 terraform.parser.<root>          Parsing 'src/cdk.tf.json'...
45:13.644685182 terraform.parser.<root>          Added file src/cdk.tf.json.
45:13.644883643 terraform.parser.<root>          Evaluating module...
45:13.646031606 terraform.parser.<root>          Read 61 block(s) and 0 ignore(s) for module 'root' (1 file[s])...
45:13.646046456 terraform.parser.<root>          Added 0 variables from tfvars.
45:13.646177634 terraform.parser.<root>          Error loading module metadata: open //src/.terraform/modules/modules.json: no such file or directory.
45:13.646196961 terraform.parser.<root>          Working directory for module evaluation is '/'
45:13.646357462 terraform.parser.<root>.evaluator Filesystem key is 'f9088d3ed2db9899500f703a07bb505300c2b5cbc122ac4365ca04af35422e64'
45:13.646385940 terraform.parser.<root>.evaluator Starting module evaluation...
45:13.652134397 terraform.parser.<root>.evaluator Starting submodule evaluation...
45:13.652151822 terraform.parser.<root>.evaluator Finished processing 0 submodule(s).
45:13.652153722 terraform.parser.<root>.evaluator Starting post-submodule evaluation...
45:13.655720895 terraform.parser.<root>.evaluator Module evaluation complete.
45:13.655746576 terraform.parser.<root>          Finished parsing module 'root'.
45:13.655787004 terraform.parser.<root>.evaluator Added module output hub-and-spoke-topology_mock-on-prem_public_ip_address_8012E98C=cty.NilVal.
45:13.655797372 terraform.executor               Adapting modules...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x82bf23]

goroutine 1 [running]:
github.com/aquasecurity/defsec/pkg/terraform.(*Block).GetMetadata(...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/pkg/terraform/block.go:135
github.com/aquasecurity/defsec/pkg/terraform.(*Attribute).AsBoolValueOrDefault(0x0?, 0x0?, 0x0?)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/pkg/terraform/attribute.go:129 +0x3c3
github.com/aquasecurity/defsec/internal/adapters/terraform/azure/compute.adaptLinuxVM(_)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/compute/adapt.go:93 +0x568
github.com/aquasecurity/defsec/internal/adapters/terraform/azure/compute.adaptCompute({0xc0001349b0, 0x1, 0x1?})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/compute/adapt.go:33 +0xcc9
github.com/aquasecurity/defsec/internal/adapters/terraform/azure/compute.Adapt(...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/compute/adapt.go:14
github.com/aquasecurity/defsec/internal/adapters/terraform/azure.Adapt({_, _, _})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/adapt.go:25 +0x12a
github.com/aquasecurity/defsec/internal/adapters/terraform.Adapt({0xc0001349b0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/adapt.go:20 +0x7e
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Executor).Execute(0xc000479a00, {0xc0001349b0?, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/pkg/scanners/terraform/executor/executor.go:96 +0x11a
github.com/aquasecurity/defsec/pkg/scanners/terraform.(*Scanner).ScanFSWithMetrics(0xc0002445a0, {0x1de3e98, 0xc00013c028}, {0x7f0b2d62b940?, 0xc000ba93a0?}, {0x7ffe26a4ef58, 0x3})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/pkg/scanners/terraform/scanner.go:216 +0x77a
github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.Root.func1(0xc000e4c900, {0xc000ba9300, 0x1, 0x2})
        /home/runner/work/tfsec/tfsec/internal/app/tfsec/cmd/root.go:83 +0x633
github.com/spf13/cobra.(*Command).execute(0xc000e4c900, {0xc000120160, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e4c900)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
main.main()
        /home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:12 +0x25
```

Note: based on the error message I thought it might be the output I have in the code.  But when I removed it as a test the memory address error still happened.

**System Info**

 - tfsec version: v1.28.1
 - terraform version: v1.3.6
 - OS: Win11 22H2

Note: I ran tfsec in windows and docker and received the same error.

**Example Code**

I have the repo here: https://github.com/JasonCubic/cdktf-az-hub-spoke-demo 
I was unable to do scope isolation beyond the stack "single-sub-hub-and-spoke" where the error occurs.

**Additional context**

I did deploy this terraform stack to azure successfully (and took it down since).  It has linux VM's on the internet with public IP's that accept ssh using a username and password.  I was expecting to see several flagged items from tfsec.

**Comment by nikpivkin** [comment]
Hi @JasonCubic !

I created the [issue](https://github.com/aquasecurity/trivy/issues/5080) in Trivy.

/cc @simar7
