### ISSUE TITLE
bug: Panic: not a string if azurerm_key_vault_key expiration_date attribute not set to static string value

### ISSUE THREAD

**Issue by HoveringHalibut** [aquasecurity/tfsec#1969]
**Describe the bug**
If the value of the expiration_data attribute of an azuremr_key_vault_key is set to null or a variable, the error "panic: not a string" is thrown.

**To Reproduce**
See example Terraform module code below.  Running tfsec against the code throws the error.

**Expected behavior**
Results are returned with a passed result for the "Key should have an expiry date specified" check.

**Output of your tfsec command with --debug flag**
17:35.971248300 system.info                      APP       tfsec.exe
17:35.971248300 system.info                      VERSION   v1.28.1
17:35.971248300 system.info                      OS        windows
17:35.972346500 system.info                      ARCH      amd64
17:35.972346500 system.info                      KERNEL
17:35.972346500 system.info                      TERM
17:35.972346500 system.info                      SHELL
17:35.972878400 system.info                      GOVERSION go1.18.7
17:35.972878400 system.info                      GOROOT    /opt/hostedtoolcache/go/1.18.7/x64
17:35.972878400 system.info                      CGO       false
17:35.972878400 system.info                      CPUCOUNT  8
17:35.973409100 system.info                      MAXPROCS  8
17:35.973409100 system.info                      WORKDIR   C:\repos\test
17:35.973409100 system.info                      UID       -1
17:35.973409100 system.info                      EUID      -1
17:35.973409100 system.info                      DOCKER    false
17:35.973935800 system.info                      CI        false
17:35.973935800 system.info                      HOSTNAME  
17:35.973935800 system.info                      TEMP      C:\Users\RICHER~1\AppData\Local\Temp
17:35.973935800 system.info                      PATHSEP   \
17:35.974459200 system.info                      CMD       C:\ProgramData\chocolatey\lib\tfsec\tools\tfsec.exe modules\terraform-azurerm-key_vault_key --debug
17:35.974459200 cmd                              Command args=[]string{"modules\\terraform-azurerm-key_vault_key"}
17:35.974982000 cmd                              Determined path dir=C:\repos\test\modules\terraform-azurerm-key_vault_key     
17:35.974982000 cmd                              Determined path root=C:
17:35.974982000 cmd                              Determined path rel=repos\test\modules\terraform-azurerm-key_vault_key        
17:35.975501900 terraform.scanner                Scanning [&{C: C:}] at 'repos\test\modules\terraform-azurerm-key_vault_key'...17:35.979382500 terraform.scanner.rego           Loaded 3 embedded libraries.
17:36.002955100 terraform.scanner.rego           Loaded 119 embedded policies.
17:36.128659400 terraform.scanner                Scanning root module 'repos\test\modules\terraform-azurerm-key_vault_key'...
17:36.129699500 terraform.parser.<root>          Setting project/module root to 'repos\test\modules\terraform-azurerm-key_vault_key'
17:36.129699500 terraform.parser.<root>          Parsing FS from 'repos/test/modules/terraform-azurerm-key_vault_key'
17:36.130660000 terraform.parser.<root>          Parsing 'repos\test\modules\terraform-azurerm-key_vault_key\locals.tf'...     
17:36.131664800 terraform.parser.<root>          Added file repos\test\modules\terraform-azurerm-key_vault_key\locals.tf.      
17:36.131664800 terraform.parser.<root>          Parsing 'repos\test\modules\terraform-azurerm-key_vault_key\main.tf'...       
17:36.131664800 terraform.parser.<root>          Added file repos\test\modules\terraform-azurerm-key_vault_key\main.tf.        
17:36.131664800 terraform.parser.<root>          Parsing 'repos\test\modules\terraform-azurerm-key_vault_key\outputs.tf'...    
17:36.132659600 terraform.parser.<root>          Added file repos\test\modules\terraform-azurerm-key_vault_key\outputs.tf.     
17:36.132659600 terraform.parser.<root>          Parsing 'repos\test\modules\terraform-azurerm-key_vault_key\variables.tf'...  
17:36.133662800 terraform.parser.<root>          Added file repos\test\modules\terraform-azurerm-key_vault_key\variables.tf.   
17:36.133662800 terraform.parser.<root>          Parsing 'repos\test\modules\terraform-azurerm-key_vault_key\version.tf'...    
17:36.133662800 terraform.parser.<root>          Added file repos\test\modules\terraform-azurerm-key_vault_key\version.tf.     
17:36.133662800 terraform.parser.<root>          Evaluating module...
17:36.135194400 terraform.parser.<root>          Read 15 block(s) and 0 ignore(s) for module 'root' (5 file[s])...
17:36.135298700 terraform.parser.<root>          Added 0 variables from tfvars.
17:36.135298700 terraform.parser.<root>          Error loading module metadata: open repos\test\modules\terraform-azurerm-key_vault_key\.terraform\modules\modules.json: invalid argument.
17:36.135298700 terraform.parser.<root>          Working directory for module evaluation is 'C:\repos\test'
17:36.135298700 terraform.parser.<root>.evaluator Filesystem key is '98d6a362eb8a41f901f5a1635aca87711499f306803437f93a9fa0f398dc83b6'
17:36.135298700 terraform.parser.<root>.evaluator Starting module evaluation...
17:36.136311800 terraform.parser.<root>.evaluator Starting submodule evaluation...
17:36.136311800 terraform.parser.<root>.evaluator Finished processing 0 submodule(s).
17:36.136311800 terraform.parser.<root>.evaluator Starting post-submodule evaluation...
17:36.136311800 terraform.parser.<root>.evaluator Module evaluation complete.
17:36.136311800 terraform.parser.<root>          Finished parsing module 'root'.
17:36.136311800 terraform.parser.<root>.evaluator Added module output expirationDate=cty.NilVal.
17:36.137310900 terraform.parser.<root>.evaluator Added module output id=cty.StringVal("09fba0b3-f2c4-4ce2-9b85-0906ce5a1c17").
17:36.137310900 terraform.parser.<root>.evaluator Added module output name=cty.NilVal.
17:36.137310900 terraform.parser.<root>.evaluator Added module output versionless_id=cty.NilVal.
17:36.137310900 terraform.executor               Adapting modules...
panic: not a string

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.AsString({{{0x0?, 0x0?}}, {0x0?, 0x0?}})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/value_ops.go:1256 +0x138
github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.adaptKey(_)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/keyvault/adapt.go:154 +0x22f
github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.(*adapter).adaptVaults(0xc0015813b0, {0xc0017a9010, 0x1, 0xc0015813c0?})      
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/keyvault/adapt.go:74 +0x1765
github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.Adapt({0xc0017a9010, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/keyvault/adapt.go:20 +0xd3
github.com/aquasecurity/defsec/internal/adapters/terraform/azure.Adapt({_, _, _})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/adapt.go:30 +0x2b7
github.com/aquasecurity/defsec/internal/adapters/terraform.Adapt({0xc0017a9010, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/adapt.go:20 +0x7e
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Executor).Execute(0xc001836100, {0xc0017a9010?, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/pkg/scanners/terraform/executor/executor.go:96 +0x11a
github.com/aquasecurity/defsec/pkg/scanners/terraform.(*Scanner).ScanFSWithMetrics(0xc0002025a0, {0x25ff5b0, 0xc00003c0e8}, {0x23fcbd2e740?, 0xc0005d5640?}, {0xc00056cba3, 0x4b})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/pkg/scanners/terraform/scanner.go:216 +0x77a
github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.Root.func1(0xc000a58c00, {0xc0005d5440, 0x1, 0x2})
        /home/runner/work/tfsec/tfsec/internal/app/tfsec/cmd/root.go:83 +0x633
github.com/spf13/cobra.(*Command).execute(0xc000a58c00, {0xc000050090, 0x2, 0x3})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000a58c00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
main.main()
        /home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:12 +0x25

**System Info**
 - tfsec version: `1.28.1`
 - terraform version: `1.3.6`
 - OS: `Windows 10`

**Example Code**
```
resource "time_static" "key_expiration" {}

variable "daysToExpiration" {
  type        = number
  description = "Number of days to key expiration.  Set to 0 to not expire."
  default     = 365
  nullable    = false
}

resource "azurerm_key_vault_key" "key" {
  name            = "testKey" #var.name
  key_vault_id    = "vauleID" #var.keyVaultId
  key_type        = "RSA" #var.keyType
  key_size        = 2048 #var.keySize
  curve           = null #var.curve
  expiration_date = var.daysToExpiration == 0 ? null : timeadd(time_static.key_expiration.rfc3339, format("%dh", (var.daysToExpiration * 24))) # "2022-12-31T00:00:00.00Z"

  key_opts = ["decrypt", "encrypt", "sign", "unwrapKey", "verify", "wrapKey"] #var.keyOpts
}
```

**Additional context**
The only way I've been able to get the test to pass is setting the expiration_date to a properly formatted RFC3339 date as a string.  Removing the expiration_date attribute allows tfsec to complete the checks with the medium finding returned.

**Comment by bhatiarahul1993** [comment]
I am facing the same issue. 

resource "azurerm_key_vault_key" "this" {
  name            = var.key_vault_key_name
  key_vault_id    = var.key_vault_id
  key_type        = var.key_type
  key_size        = var.key_size
  expiration_date = var.expiration_date 
  key_opts        = var.key_opts
  not_before_date = var.not_before_date
  tags            = local.tags
}

Output:

panic: not a string

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.AsString({{{0x0?, 0x0?}}, {0x0?, 0x0?}})
        /home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/value_ops.go:1256 +0x138
github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.adaptKey(_)
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/keyvault/adapt.go:154 +0x22f
github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.(*adapter).adaptVaults(0xc0017c13b0, {0xc0006b5e80, 0x2, 0xc0017c13c0?})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/keyvault/adapt.go:74 +0x1765
github.com/aquasecurity/defsec/internal/adapters/terraform/azure/keyvault.Adapt({0xc0006b5e80, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/keyvault/adapt.go:20 +0xd3
github.com/aquasecurity/defsec/internal/adapters/terraform/azure.Adapt({_, _, _})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/azure/adapt.go:30 +0x2b7
github.com/aquasecurity/defsec/internal/adapters/terraform.Adapt({0xc0006b5e80, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/internal/adapters/terraform/adapt.go:20 +0x7e
github.com/aquasecurity/defsec/pkg/scanners/terraform/executor.(*Executor).Execute(0xc0014c5500, {0xc0006b5e80?, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/pkg/scanners/terraform/executor/executor.go:96 +0x11a
github.com/aquasecurity/defsec/pkg/scanners/terraform.(*Scanner).ScanFSWithMetrics(0xc0001fe1e0, {0x27df5b0, 0xc00003c0d0}, {0x1f46ade50c0?, 0xc000b38160?}, {0xc000ad4093, 0x1f})
        /home/runner/go/pkg/mod/github.com/aquasecurity/defsec@v0.82.2/pkg/scanners/terraform/scanner.go:216 +0x77a
github.com/aquasecurity/tfsec/internal/app/tfsec/cmd.Root.func1(0xc000866900, {0x34593a8, 0x0, 0x0})
        /home/runner/work/tfsec/tfsec/internal/app/tfsec/cmd/root.go:83 +0x633
github.com/spf13/cobra.(*Command).execute(0xc000866900, {0xc000074220, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000866900)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
main.main()
        /home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:12 +0x25
        
        
        
  Working only when I am passing a static value to the argument "expiration_date"  in the resource block.

**Comment by nikpivkin** [comment]
Hi @HoveringHalibut  !

This has been [fixed](https://github.com/aquasecurity/defsec/issues/1024). You can use Trivy to scan the configuration, because tfsec is [part of it](https://github.com/aquasecurity/tfsec/discussions/1994).
